language: java

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get install -y curl netcat

install:
  - docker build -t krow7/hlds:1.1 .
  - docker-compose up -d
  - sleep 70
  - docker ps -a

script:
  - chmod 744 files/hc.sh
  - files/hc.sh "." > /dev/null || exit 1