language: minimal

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get install -y netcat

install:
  - docker build -t krow7/hlds:test .
  - docker-compose up -d
  - sleep 70
  - docker ps -a

script:
  - chmod 744 files/hc.sh
  - files/hc.sh "." > /dev/null || exit 1

after_success:
  - chmod 744 .travis/push.sh
  - .travis/push.sh $DOCKER_LOGIN $DOCKER_PASS $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST || exit 1