language: minimal

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get install -y netcat
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST

install:
  - chmod 744 .travis/build_and_check.sh
  - .travis/build_and_check.sh || exit 1

script:
  - chmod 744 files/hc.sh
  - files/hc.sh "." > /dev/null || exit 1

after_success:
  - chmod 744 .travis/push.sh
  - .travis/push.sh $DOCKER_LOGIN $DOCKER_PASS $TRAVIS_BRANCH $TRAVIS_PULL_REQUEST || exit 1