language: java

services:
  - docker

before-install:
  - sudo apt-get update
  - sudo apt-get install -y curl netcat

install:
  - docker build -t krow7/hlds:1.1 .
  - docker-compose up -d
  - docker ps -a

script:
  - sh files/hc.sh "." || exit 1
  - cat answer.dat