language: java

services:
  - docker
env:
  global:
    - HLDS_PATH="."

install:
  - docker build -t krow7/hlds:1.1 .
  - docker-compose up -d
  - docker ps -a

script:
  - chmod 744 files/hc.sh
  - files/hc.sh > /dev/null || exit 1