version: '3'
services:
  hlds:
    image: rooooomka/hlds-docker:2.0
    container_name: hlds
    platform: linux/amd64
    ports:
      - "27015:27015/udp"
    volumes:
      - "hldsvol:/home/steam/opts"

volumes:
  hldsvol:
